#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fahrzeugtypen-Mapping für Leitstellenspiel.de
Quelle: https://www.leitstellenspiel.de/fahrzeuge
"""

# Mapping von Fahrzeugtyp-ID zu Fahrzeugtyp-Name und Kategorie
VEHICLE_TYPES = {
    # Feuerwehr
    0: {'name': 'LF 20', 'category': 'LF', 'short': 'LF'},
    1: {'name': 'LF 10', 'category': 'LF', 'short': 'LF'},
    2: {'name': 'DLK 23', 'category': 'DLK', 'short': 'DLK'},
    3: {'name': 'ELW 1', 'category': 'ELW', 'short': 'ELW'},
    4: {'name': 'RW', 'category': 'RW', 'short': 'RW'},
    5: {'name': 'GW-A', 'category': 'GW-A', 'short': 'GW-A'},
    6: {'name': 'LF 8/6', 'category': 'LF', 'short': 'LF'},
    7: {'name': 'LF 20/16', 'category': 'LF', 'short': 'LF'},
    8: {'name': 'LF 10/6', 'category': 'LF', 'short': 'LF'},
    9: {'name': 'LF 16-TS', 'category': 'LF', 'short': 'LF'},
    10: {'name': 'GW-Öl', 'category': 'GW-Öl', 'short': 'GW-Öl'},
    11: {'name': 'GW-L2-Wasser', 'category': 'GW-L2', 'short': 'GW-L2'},
    12: {'name': 'GW-Messtechnik', 'category': 'GW-Mess', 'short': 'GW-Mess'},
    13: {'name': 'SW 1000', 'category': 'SW', 'short': 'SW'},
    14: {'name': 'SW 2000', 'category': 'SW', 'short': 'SW'},
    15: {'name': 'SW 2000-Tr', 'category': 'SW', 'short': 'SW'},
    16: {'name': 'SW Kats', 'category': 'SW', 'short': 'SW'},
    17: {'name': 'TLF 4000', 'category': 'TLF', 'short': 'TLF'},
    18: {'name': 'TLF 3000', 'category': 'TLF', 'short': 'TLF'},
    19: {'name': 'TLF 2000', 'category': 'TLF', 'short': 'TLF'},
    20: {'name': 'TLF 16/25', 'category': 'TLF', 'short': 'TLF'},
    21: {'name': 'TLF 16/45', 'category': 'TLF', 'short': 'TLF'},
    22: {'name': 'GW-Gefahrgut', 'category': 'GW-G', 'short': 'GW-G'},
    23: {'name': 'RTW', 'category': 'RTW', 'short': 'RTW'},
    24: {'name': 'NEF', 'category': 'NEF', 'short': 'NEF'},
    25: {'name': 'HLF 20', 'category': 'LF', 'short': 'LF'},
    26: {'name': 'RTH', 'category': 'RTH', 'short': 'RTH'},
    27: {'name': 'FuStW', 'category': 'FuStW', 'short': 'FuStW'},
    28: {'name': 'GW-Höhenrettung', 'category': 'GW-Höhe', 'short': 'GW-Höhe'},
    29: {'name': 'ELW 2', 'category': 'ELW', 'short': 'ELW'},
    30: {'name': 'leBefKw', 'category': 'leBefKw', 'short': 'leBefKw'},
    31: {'name': 'MTW', 'category': 'MTW', 'short': 'MTW'},
    32: {'name': 'TSF-W', 'category': 'TSF', 'short': 'TSF'},
    33: {'name': 'KTW', 'category': 'KTW', 'short': 'KTW'},
    34: {'name': 'GW-Taucher', 'category': 'GW-Taucher', 'short': 'GW-Taucher'},
    35: {'name': 'GKW', 'category': 'GKW', 'short': 'GKW'},
    36: {'name': 'MTW-TZ', 'category': 'MTW', 'short': 'MTW'},
    37: {'name': 'MZF', 'category': 'MZF', 'short': 'MZF'},
    38: {'name': 'LKW K9', 'category': 'K9', 'short': 'K9'},
    39: {'name': 'BRmG R', 'category': 'BRmG', 'short': 'BRmG'},
    40: {'name': 'Anh DLE', 'category': 'Anh', 'short': 'Anh'},
    41: {'name': 'MLW 5', 'category': 'MLW', 'short': 'MLW'},
    42: {'name': 'WLF', 'category': 'WLF', 'short': 'WLF'},
    43: {'name': 'AB-Rüst', 'category': 'AB', 'short': 'AB'},
    44: {'name': 'AB-Atemschutz', 'category': 'AB', 'short': 'AB'},
    45: {'name': 'AB-Öl', 'category': 'AB', 'short': 'AB'},
    46: {'name': 'GruKw', 'category': 'GruKw', 'short': 'GruKw'},
    47: {'name': 'FüKw', 'category': 'FüKw', 'short': 'FüKw'},
    48: {'name': 'GefKw', 'category': 'GefKw', 'short': 'GefKw'},
    49: {'name': 'Dekon-P', 'category': 'Dekon', 'short': 'Dekon'},
    50: {'name': 'AB-Dekon-P', 'category': 'AB', 'short': 'AB'},
    51: {'name': 'AB-Schlauch', 'category': 'AB', 'short': 'AB'},
    52: {'name': 'GW-Werkfeuerwehr', 'category': 'GW', 'short': 'GW'},
    53: {'name': 'ULF mit Löscharm', 'category': 'ULF', 'short': 'ULF'},
    54: {'name': 'TM 50', 'category': 'TM', 'short': 'TM'},
    55: {'name': 'Turbolöscher', 'category': 'Turbo', 'short': 'Turbo'},
    56: {'name': 'TLF 8/18', 'category': 'TLF', 'short': 'TLF'},
    57: {'name': 'FLF', 'category': 'FLF', 'short': 'FLF'},
    58: {'name': 'Rettungstreppe', 'category': 'Rettungstreppe', 'short': 'Rettungstreppe'},
    59: {'name': 'AB-Einsatzleitung', 'category': 'AB', 'short': 'AB'},
    60: {'name': 'SEK - ZF', 'category': 'SEK', 'short': 'SEK'},
    61: {'name': 'SEK - MTF', 'category': 'SEK', 'short': 'SEK'},
    62: {'name': 'MEK - ZF', 'category': 'MEK', 'short': 'MEK'},
    63: {'name': 'MEK - MTF', 'category': 'MEK', 'short': 'MEK'},
    64: {'name': 'GW-Wasserrettung', 'category': 'GW-Wasser', 'short': 'GW-Wasser'},
    65: {'name': 'LKW 7 Lkr 19 tm', 'category': 'LKW', 'short': 'LKW'},
    66: {'name': 'Anh MzB', 'category': 'Anh', 'short': 'Anh'},
    67: {'name': 'Anh SchlB', 'category': 'Anh', 'short': 'Anh'},
    68: {'name': 'Anh MzAB', 'category': 'Anh', 'short': 'Anh'},
    69: {'name': 'Tauchkraftwagen', 'category': 'Tauch', 'short': 'Tauch'},
    70: {'name': 'MZB', 'category': 'MZB', 'short': 'MZB'},
    71: {'name': 'AB-MZB', 'category': 'AB', 'short': 'AB'},
    72: {'name': 'WaWe 10', 'category': 'WaWe', 'short': 'WaWe'},
    73: {'name': 'GRTW', 'category': 'GRTW', 'short': 'GRTW'},
    74: {'name': 'NAW', 'category': 'NAW', 'short': 'NAW'},
    75: {'name': 'FLF (Airport)', 'category': 'FLF', 'short': 'FLF'},
    76: {'name': 'Rettungstreppe (Airport)', 'category': 'Rettungstreppe', 'short': 'Rettungstreppe'},
    77: {'name': 'AB-Gefahrgut', 'category': 'AB', 'short': 'AB'},
    78: {'name': 'AB-Einsatzleitung', 'category': 'AB', 'short': 'AB'},
    79: {'name': 'GRTW (Intensivtransport)', 'category': 'GRTW', 'short': 'GRTW'},
    80: {'name': 'KdoW-LNA', 'category': 'KdoW', 'short': 'KdoW'},
    81: {'name': 'KdoW-OrgL', 'category': 'KdoW', 'short': 'KdoW'},
    82: {'name': 'KTW Typ B', 'category': 'KTW', 'short': 'KTW'},
    83: {'name': 'ELW 1 (SEG)', 'category': 'ELW', 'short': 'ELW'},
    84: {'name': 'GW-San', 'category': 'GW-San', 'short': 'GW-San'},
    85: {'name': 'Polizeihubschrauber', 'category': 'Polizeihubschrauber', 'short': 'Polizeihubschrauber'},
    86: {'name': 'AB-Sanitätsdienst', 'category': 'AB', 'short': 'AB'},
    87: {'name': 'Boot', 'category': 'Boot', 'short': 'Boot'},
    88: {'name': 'HLF 10', 'category': 'LF', 'short': 'LF'},
    89: {'name': 'Zivilstreifenwagen', 'category': 'FuStW', 'short': 'FuStW'},
    90: {'name': 'Außenlastbehälter allgemein', 'category': 'ALB', 'short': 'ALB'},
    91: {'name': 'ITH', 'category': 'ITH', 'short': 'ITH'},
}

# Mapping von Kategorie zu möglichen Fahrzeugtyp-IDs
CATEGORY_TO_TYPES = {}
for type_id, info in VEHICLE_TYPES.items():
    category = info['short']
    if category not in CATEGORY_TO_TYPES:
        CATEGORY_TO_TYPES[category] = []
    CATEGORY_TO_TYPES[category].append(type_id)

